config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  # resources :events
  resources :events do
    member do
      delete :destroy
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Trying out our weather route
  get '/weather/:city', to: 'weather#show', as: 'weather'

  # Defines the root path route ("/")
  # root "posts#index"
  root 'events#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController

    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(event_params)

        if @event.save
            redirect_to @event, notice: 'Event was successfully created.'
        else
            render :new
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])

        if @event.update(event_params)
            redirect_to @event, notice: 'Event was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy

        redirect_to events_url, notice: 'Event was successfully destroyed.'
    end

    private

    def event_params
        params.require(:event).permit(:title, :description, :start_date, :end_date, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!

    def index
        
        # handling special case for passing parameter to endpoint enabling viewing of all active events
        @events = params[:show_all] == 'true' ? Event.all : (current_user ? current_user.events : [])

        respond_to do |format|
            format.html { render :index } 
            format.json { render json: @events }
        end
    end

    def show
        # @event = Event.find(params[:id])
        @events = params[:show_all] == 'true' ? Event.all : (current_user ? current_user.events : [])

        respond_to do |format|
            format.html { render :index } 
            format.json { render json: @events }
        end
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(event_params)

        if @event.save
            redirect_to events_path, notice: 'Event was successfully created.'
        else
            render :index
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])

        if @event.update(event_params)
            redirect_to @event, notice: 'Event was successfully updated.'
        else
            flash[:alert] = 'Error updating event.'
            render :edit
        end
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy

        redirect_to events_url, notice: 'Event was successfully destroyed.'
    end

    private

    def event_params
        params.require(:event).permit(:title, :description, :location, :start_date, :end_date, :user_id)
    end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
    before_action :authenticate_user!
    
    def show
        api_key = ENV['WEATHER_API_KEY']
        Rails.logger.info("API Key: #{api_key}")
        @weather_service = WeatherService.new(api_key)
        @city = params[:city] || 'Dublin'
        @weather_data = @weather_service.get_weather(@city)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edit Event</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
<body>
  <h2>Edit Event</h2>

  <%= form_with(model: @event, url: event_path(@event), method: :patch) do |form| %>
    <div style="display: flex; flex-direction: column; gap: 1em;">
      <div style="display: flex; align-items: center; margin-bottom: 1em;">
        <div style="width: 100px;">
          <%= form.label :title %>
        </div>
        <%= form.text_field :title %>
      </div>

      <div style="display: flex; align-items: center; margin-bottom: 1em;">
        <div style="width: 100px;">
          <%= form.label :description %>
        </div>
        <%= form.text_area :description %>
      </div>

      <div style="display: flex; align-items: center; margin-bottom: 1em;">
        <div style="width: 100px;">
          <%= form.label :start_date %>
        </div>
        <%= form.datetime_local_field :start_date %>
      </div>

      <div style="display: flex; align-items: center; margin-bottom: 1em;">
        <div style="width: 100px;">
          <%= form.label :end_date %>
        </div>
        <%= form.datetime_local_field :end_date %>
      </div>

      <div style="display: flex; align-items: center; margin-bottom: 1em;">
        <div style="width: 100px;">
          <%= form.label :location %>
        </div>
        <%= form.text_field :location %>
      </div>

      <div>
        <%= form.submit "Update Event" %>
      </div>
    </div>
  <% end %>

  <br/>

  <%= link_to "Back to Events", @event %>

  <% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %></p>
  <% end %>
</body>
</html>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Planner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- delete endpoing bugging witha  get instead of delete requset on click thought this might help... -->
    <%= javascript_include_tag 'rails-ujs', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
        <h2>Registered Events</h2>

        <table>
        <thead>
            <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Location</th>
            </tr>
        </thead>
        <tbody>
            <% @events.each do |event| %>
            <tr>
                <td><%= event.title %></td>
                <td><%= event.description %></td>
                <td><%= event.start_date %></td>
                <td><%= event.end_date %></td>
                <td><%= event.location %></td>
                <td><%= link_to "Edit", edit_event_path(event) %></td>
                <td><%= link_to "Delete", event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
        </table>

        <%= link_to "Show All Users Events", events_path(show_all: true), class: "show-all-link" %>
        <%= link_to "Show My Events", events_path, class: "show-my-events-link" %>
    </div>

    <hr />

    <div>
        <h2>Create an Event</h2>

        <%= form_with(model: Event.new, url: events_path, method: :post) do |form| %>
            <div style="display: flex; flex-direction: column; gap: 1em;">
                <div style="display: flex; align-items: center; margin-bottom: 1em;">
                <div style="width: 100px;">
                    <%= form.label :title %>
                </div>
                <%= form.text_field :title %>
                </div>

                <div style="display: flex; align-items: center; margin-bottom: 1em;">
                <div style="width: 100px;">
                    <%= form.label :description %>
                </div>
                <%= form.text_area :description %>
                </div>

                <div style="display: flex; align-items: center; margin-bottom: 1em;">
                <div style="width: 100px;">
                    <%= form.label :start_date %>
                </div>
                <%= form.datetime_local_field :start_date %>
                </div>

                <div style="display: flex; align-items: center; margin-bottom: 1em;">
                <div style="width: 100px;">
                    <%= form.label :end_date %>
                </div>
                <%= form.datetime_local_field :end_date %>
                </div>

                <div style="display: flex; align-items: center; margin-bottom: 1em;">
                <div style="width: 100px;">
                    <%= form.label :location %>
                </div>
                <%= form.text_field :location %>
                </div>

                <div>
                <%= form.submit "Create Event" %>
                </div>
            </div>
        <% end %>
    </div>
    
    <hr />

    <div>
        <a href="/weather/Dublin">Checkout Current Forecast</a>
    </div>

    <hr />

    <div>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' } %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Planner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/show.html.erb
<h1>Current Weather for <%= @city %></h1>

<div>
  <% if @weather_data %>
    <p>Temperature: <%= @weather_data['main']['temp'] %>°C</p>
    <p>Conditions: <%= @weather_data['weather'][0]['description'] %></p>
  <% else %>
    <p>Unable to retrieve weather data for <%= @city %></p>
  <% end %>

  <div>
      <a href="/events">Return to Events</a>
  </div>
</div>